name: 'IB&G'
favicon: null
layout_spectrum: 0.24892
typography_spectrum: 0.52127
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#323232'
    - '#c2cc5a'
    - '#7b7b7b'
    - '#090909'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
