name: 'IB&G'
favicon: null
layout_spectrum: 0.7636
typography_spectrum: 0.60841
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#323232'
    - '#c2cc5a'
    - '#7b7b7b'
    - '#090909'
  brandStrength: 0.5525325320195407
  lightness: 0.375
  saturation: 0.5768601498566568
  rhythmicContrast: 0.5
purpose: []
